appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
JellyfinServerHttp:
  port: 9096
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts:
- hostPath: /mnt/extras/something
  mountPath: /mnt/extras
  readOnly: true
gpuConfiguration: {}
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: linuxserver/jellyfin
  tag: 10.8.1
updateStrategy: Recreate
